    let dados = [
        {
            idioma : "Para aprender Inglês",
            iniciante : "Iniciante",
            tituloiniciante : "Learn English with BBC",
            descricaoiniciante : "Podcast da BBC com lições simples e claras, ideal para quem está começando a aprender o idioma.",
            linkiniciante : "https://open.spotify.com/search/Learn%20English%20with%20BBC/podcastAndEpisodes",
            intermediario : "Intermediário",
            titulointermediario : "Luke's English Podcast",
            descricaointermediario : "Podcast com diversos temas e um estilo mais informal, ideal para quem já tem uma base em inglês e quer aprimorar a compreensão e a fluência.",
            linkintermediario : "https://open.spotify.com/show/4X48gpjrctXNJWtOnUgwq8",
            avancado : "Avançado",
            tituloavancado : "Grammar Girl",
            descricaoavancado : "Podcast com dicas e explicações sobre gramática inglesa, ideal para quem busca aperfeiçoar suas habilidades linguísticas.",
            linkavancado : "https://open.spotify.com/show/3gRQiaxv3M01MxxBIMxkAy",
            tags: "inglesa, english, ingles"
        },
        {
            idioma : "Para aprender Espanhol",
            iniciante : "Iniciante",
            tituloiniciante : "Hoy Hablamos",
            descricaoiniciante : "Podcast diário com notícias e temas do cotidiano em espanhol, apresentado de forma clara e concisa.",
            linkiniciante : "https://open.spotify.com/show/1puKUN2oF1M5DMt8o4M1bA",
            intermediario : "Intermediário",
            titulointermediario : "Español Intermedio",
            descricaointermediario : "Podcast que aborda diversos temas relacionados aos países latinos, além de ensinar novas palavras e expressões.",
            linkintermediario : "https://open.spotify.com/show/0m12I8eatCl3HJ4U3i1704",
            avancado : "Avançado",
            tituloavancado : "Notes in Spanish",
            descricaoavancado : "Além das aulas mais aprofundadas, o podcast oferece também episódios com entrevistas e conversas em espanhol.",
            linkavancado : "https://open.spotify.com/show/6kf6aCHaI9WsPVL2PuvRom",
            tags: "spanish, español, espanhola, espanol"
        },
        {
            idioma : "Para aprender Francês",
            iniciante : "Iniciante",
            tituloiniciante : "Easy French",
            descricaoiniciante : "Podcast com lições curtas e práticas em francês, ideal para quem está começando a aprender o idioma.",
            linkiniciante : "https://open.spotify.com/show/6ymiUbRF2qUuQGqpNsGjFC",
            intermediario : "Intermediário",
            titulointermediario : "News in Slow French",
            descricaointermediario : "Podcast com notícias em francês adaptadas para níveis intermediários, com transcrições e explicações.",
            linkintermediario : "https://open.spotify.com/show/3sbOvAVL6IIdMjop1r4i1G",
            avancado : "Avançado",
            tituloavancado : "Coffee Break French",
            descricaoavancado : "Podcast com lições mais longas e aprofundadas sobre gramática e vocabulário em francês, ideal para quem busca um aprendizado mais completo.",
            linkavancado : "https://open.spotify.com/show/6YqgG1UezfW9khCvLh8rvw",
            tags: "french, francesa"
        },
    ];
